name: Minigames
version: '${project.version}'
main: com.trxsh.minigames.Main
api-version: 1.19
authors: [ trxsh ]
description: Minigames!!!
commands:
  start:
    description: starts a minigame
    command: /<command>
